### ISSUE TITLE
Unable to get the changed text from vs code client

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/coala-langserver#1]
The client gets an error every time the text is changed:

```text
workbench.main.js:132 Cannot read property 'trigger' of undefined: TypeError: Cannot read property 'trigger' of undefined
    at LanguageClient.onDidChangeTextDocument (/Users/gaoce/Projects/GitHub/coala-langserver/vscode-client/node_modules/vscode-languageclient/lib/main.js:697:38)
    at /Users/gaoce/Projects/GitHub/coala-langserver/vscode-client/node_modules/vscode-languageclient/lib/main.js:570:88
    at e.invoke (/Users/gaoce/Files/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:31992)
    at e.fire (/Users/gaoce/Files/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:8945)
    at t.$acceptModelChanged (/Users/gaoce/Files/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:11:686)
    at t.e.handle (/Users/gaoce/Files/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:10:4203)
    at s (/Users/gaoce/Files/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:7:11178)
    at p (/Users/gaoce/Files/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:7:11855)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ workbench.main.js:132(anonymous function) @ workbench.main.js:132e.onUnexpectedError @ workbench.main.js:30o @ workbench.main.js:30t.onUnexpectedExtHostError @ workbench.main.js:109e.handle @ workbench.main.js:108s @ workbench.main.js:50f @ workbench.main.js:50_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

**Comment by at15** [comment]
你们说这个bug吼不吼

**Comment by gaocegege** [comment]
The bug is caused by wrong config in `initial` response:

```
{"jsonrpc":"2.0","id":0,"result":{"capabilities":{}}}
```

should be

```
{"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":1}}}
```
